on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

name: "Linter"
jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up linters
        run: sudo apt-get update && sudo apt-get install -y shellcheck shfmt
      - name: Run ShellCheck
        run: make lint
